In [ ]:
# Cargamos las librerias necesarias
library(dplyr)
library(tidyverse)
library(modeest)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘timeDate’, ‘timeSeries’, ‘gss’, ‘rmutil’, ‘clue’, ‘fBasics’, ‘stable’, ‘stabledist’, ‘statip’

# **UNIDAD 2**: *Estadística*
<p style="margin-top: 15px;">
  <b><font size="4" color="gray">Tipos de variables (discreta, continua). Distribución de frecuencias y medidas descriptivas (medidas de posición y de dispersión)</font></b>
</p>

## Tablas de frecuencias

<p style="margin-top: 0px;">
  <b><font size="4">Código básico:</font></b>
</p>

<p style="margin-top: 15px;">
  <b><font size="4" color="gray">Datos correspondientes a una variable cuantitativa:</font></b>
</p>


- Pocos valores distintos
- Muchos valores distintos

In [ ]:
# Creamos el vector con los datos
datos <- c(18.5, 19.2, 20.1, 21.3, 22.5, 20.8, 19.7, 21.0, 20.4, 19.9, 22.1, 21.7, 20.6, 21.2, 20.3, 22.0, 21.5, 19.5, 20.0, 21.9)

In [ ]:
# Verificamos la condición
n_distintos <- length(unique(datos))
umbral <- 10  # Usualmente son 10/15

cat("La cantidad de valores distintos es de:", n_distintos, "\n")

# Si la cantidad de valores distintos es menor o igual al umbral propuesto, realizamos una tabla no agrupada, caso contrario realizamos una tabla agrupada por intervalos
if (n_distintos <= umbral) {
  cat("Como hay menos o igual a", umbral, "valores distintos, realizamos una 'Tabla no agrupada'\n\n")

  tabla_frecuencias <- tibble(xi = sort(datos)) %>%
    count(xi, name = "fi") %>%
    mutate(
      Fi = cumsum(fi),
      fri = fi / sum(fi),
      Fri = cumsum(fri),
      pi = round(fri * 100, 2),
      Pi = round(Fri * 100, 2)
    )

}else {

  cat("Como hay más de", umbral, "valores distintos, realizamos una 'Tabla agrupada por intervalos'\n\n")

  # Valor mínimo
  x_min <- min(datos)

  # Valor máximo
  x_max <- max(datos)

  # Tamaño de la muestra
  n <- length(datos)

  # Número de clases
  k <- ceiling(sqrt(n))

  # Ancho o amplitud de la clase
  A <- ceiling((x_max - x_min) / k)

  # Límite inicial (redondeado hacia abajo)
  L0 <- floor(x_min)

  # Sumamos la amplitud sucesivamente hasta superar el máximo
  cortes <- seq(from = L0, to = x_max + A, by = A)

  # Creamos la tabla de frecuencia
  tabla_frecuencias <- tibble(x = datos) %>%
    mutate(intervalo = cut(x, breaks = cortes, right = FALSE, include.lowest = TRUE)) %>%
    count(intervalo, name = "fi") %>%
    mutate(
      xi = cortes[1:n()] + (A / 2),
      Fi = cumsum(fi),
      fri = fi / sum(fi),
      Fri = cumsum(fri),
      pi = round(fri * 100, 2),
      Pi = round(Fri * 100, 2)
    )
}

tabla_frecuencias

La cantidad de valores distintos es de: 20
Como hay más de 10 valores distintos, realizamos una 'Tabla agrupada por intervalos'

  intervalo fi xi   Fi fri  Fri  pi Pi
1 [18,19)   1  18.5  1 0.05 0.05  5   5
2 [19,20)   4  19.5  5 0.20 0.25 20  25
3 [20,21)   6  20.5 11 0.30 0.55 30  55
4 [21,22)   6  21.5 17 0.30 0.85 30  85
5 [22,23]   3  22.5 20 0.15 1.00 15 100

### Regla FD (Freedman–Diaconis)

In [ ]:
# Creamos el vector con los datos
entrada <- c(18.5, 19.2, 20.1, 21.3, 22.5, 20.8, 19.7, 21.0, 20.4, 19.9, 22.1, 21.7, 20.6, 21.2, 20.3, 22.0, 21.5, 19.5, 20.0, 21.9)

In [ ]:
# Creamos la tabla de frecuencia
tabla_FD <- tibble(variable = valores_vector) %>%
  mutate(variable = as.numeric(variable)) %>%
  filter(!is.na(variable)) %>%
  mutate(intervalo = cut(variable, breaks = nclass.FD(variable), include.lowest = TRUE, right = FALSE)) %>%
  count(intervalo, name = "fi") %>%
  mutate(
    lim_inf = as.numeric(sub("\\[|\\(", "", sub(",.*", "", intervalo))),
    lim_sup = as.numeric(sub(".*,", "", sub("\\]|\\)", "", intervalo))),
    xi = (lim_inf + lim_sup) / 2,
    Fi = cumsum(fi),
    fri = fi / sum(fi),
    Fri = cumsum(fri),
    pi = round(fri * 100, 2),
    Pi = round(Fri * 100, 2)
  ) %>%
  select(intervalo, xi, fi, Fi, fri, Fri, pi, Pi)

tabla_FD

  intervalo   xi fi Fi fri  Fri  pi Pi
1 [18.5,19.5) 19 2   2 0.10 0.10 10  10
2 [19.5,20.5) 20 7   9 0.35 0.45 35  45
3 [20.5,21.5) 21 5  14 0.25 0.70 25  70
4 [21.5,22.5] 22 6  20 0.30 1.00 30 100

### Regla de Sturges

In [ ]:
# Creamos la tabla de frecuencias
tabla_Sturges <- tibble(variable = valores_vector) %>%
  mutate(variable = as.numeric(variable)) %>%
  filter(!is.na(variable)) %>%
  mutate(intervalo = cut(variable, breaks = nclass.Sturges(variable), include.lowest = TRUE, right = FALSE)) %>%
  count(intervalo, name = "fi") %>%
  mutate(
    lim_inf = as.numeric(sub("\\[|\\(", "", sub(",.*", "", intervalo))),
    lim_sup = as.numeric(sub(".*,", "", sub("\\]|\\)", "", intervalo))),
    xi = (lim_inf + lim_sup) / 2,
    Fi = cumsum(fi),
    fri = fi / sum(fi),
    Fri = cumsum(fri),
    pi = round(fri * 100, 2),
    Pi = round(Fri * 100, 2)
  ) %>%
  select(intervalo, xi, fi, Fi, fri, Fri, pi, Pi)

tabla_Sturges

  intervalo   xi    fi Fi fri  Fri  pi Pi
1 [18.5,19.2) 18.85 1   1 0.05 0.05  5   5
2 [19.2,19.8) 19.50 3   4 0.15 0.20 15  20
3 [19.8,20.5) 20.15 5   9 0.25 0.45 25  45
4 [20.5,21.2) 20.85 3  12 0.15 0.60 15  60
5 [21.2,21.8) 21.50 4  16 0.20 0.80 20  80
6 [21.8,22.5] 22.15 4  20 0.20 1.00 20 100

## Medidas descriptivas

In [ ]:
# Armamos el vector con los datos
datos <- c(12, 15, 14, 10, 18, 15, 16, 14, 19, 20, 15, 17, 13, 11, 14, 16, 22, 15, 13, 14)

In [ ]:
# Calculamos los descriptivos
descriptivos <- tibble(
  conteo   = length(datos),
  media    = round(mean(datos, na.rm = TRUE), 2),
  varianza = round(var(datos, na.rm = TRUE), 2),
  desvio   = round(sd(datos, na.rm = TRUE), 2),
  moda     = paste(mfv(datos), collapse = ", "),
  minimo   = round(min(datos, na.rm = TRUE), 2),
  maximo   = round(max(datos, na.rm = TRUE), 2),
  IQR      = round(IQR(datos, na.rm = TRUE), 2),
  rango    = maximo - minimo,
  mediana  = round(median(datos, na.rm = TRUE), 2),
  Q1       = round(quantile(datos, 0.25, na.rm = TRUE), 2),
  Q3       = round(quantile(datos, 0.75, na.rm = TRUE), 2),
  sup.     = round((Q3 + 1.5 * IQR), 2),
  inf.     = round((Q1 - 1.5 * IQR), 2),
  CV       = round(sd(datos, na.rm = TRUE) / mean(datos, na.rm = TRUE) * 100, 2)
)

descriptivos

    conteo media varianza desvio moda   minimo maximo IQR rango mediana Q1
25% 20     15.15 8.77     2.96   14, 15 10     22     2.5 12    15      13.75
    Q3    sup. inf. CV
25% 16.25 20   10   19.54